package maces.phase

import maces._
import maces.annotation._

import os._

case class PDKNameAnnotationValue(value: String) extends AnnotationValue

object LibraryNotFoundException extends Exception

case class DigestASPA7LibraryAnnotation(scratchPadIn: ScratchPad) extends Phase with HasTarCache {
  def asap7Annotations = Set(
    Annotation("system.library.asap7.libraries.ao_rvt_ss", LibraryAnnotationValue(Library(name = "ao_rvt_ss", voltage = 0.63, temperature = 100, nominalType = "ss",
      libertyFile = Some(???),
      voltageThreshold = Some("rvt"),
      qrcTechFile = Some(???),
      lefFile = Some(???),
      spiceFile = Some(???),
      gdsFile = Some(???)))),
    Annotation("system.library.asap7.libraries.ao_rvt_tt", LibraryAnnotationValue(Library(name = "ao_rvt_tt", voltage = 0.7, temperature = 25, nominalType = "tt",
      libertyFile = Some(???),
      voltageThreshold = Some("rvt"),
      qrcTechFile = Some(???),
      lefFile = Some(???),
      spiceFile = Some(???),
      gdsFile = Some(???)))),
    Annotation("system.library.asap7.libraries.ao_rvt_ff", LibraryAnnotationValue(Library(name = "ao_rvt_ff", voltage = 0.7, temperature = 0, nominalType = "ff",
      libertyFile = Some(???),
      voltageThreshold = Some("rvt"),
      qrcTechFile = Some(???),
      lefFile = Some(???),
      spiceFile = Some(???),
      gdsFile = Some(???)))),
    Annotation("system.library.asap7.libraries.invbuf_rvt_ss", LibraryAnnotationValue(Library(name = "invbuf_rvt_ss", voltage = 0.63, temperature = 100, nominalType = "ss",
      libertyFile = Some(???),
      voltageThreshold = Some("rvt"),
      qrcTechFile = Some(???),
      lefFile = Some(???),
      spiceFile = Some(???),
      gdsFile = Some(???)))),
    Annotation("system.library.asap7.libraries.invbuf_rvt_tt", LibraryAnnotationValue(Library(name = "invbuf_rvt_tt", voltage = 0.7, temperature = 25, nominalType = "tt",
      libertyFile = Some(???),
      voltageThreshold = Some("rvt"),
      qrcTechFile = Some(???),
      lefFile = Some(???),
      spiceFile = Some(???),
      gdsFile = Some(???)))),
    Annotation("system.library.asap7.libraries.invbuf_rvt_ff", LibraryAnnotationValue(Library(name = "invbuf_rvt_ff", voltage = 0.7, temperature = 0, nominalType = "ff",
      libertyFile = Some(???),
      voltageThreshold = Some("rvt"),
      qrcTechFile = Some(???),
      lefFile = Some(???),
      spiceFile = Some(???),
      gdsFile = Some(???)))),
    Annotation("system.library.asap7.libraries.oa_rvt_ss", LibraryAnnotationValue(Library(name = "oa_rvt_ss", voltage = 0.63, temperature = 100, nominalType = "ss",
      libertyFile = Some(???),
      voltageThreshold = Some("rvt"),
      qrcTechFile = Some(???),
      lefFile = Some(???),
      spiceFile = Some(???),
      gdsFile = Some(???)))),
    Annotation("system.library.asap7.libraries.oa_rvt_tt", LibraryAnnotationValue(Library(name = "oa_rvt_tt", voltage = 0.7, temperature = 25, nominalType = "tt",
      libertyFile = Some(???),
      voltageThreshold = Some("rvt"),
      qrcTechFile = Some(???),
      lefFile = Some(???),
      spiceFile = Some(???),
      gdsFile = Some(???)))),
    Annotation("system.library.asap7.libraries.oa_rvt_ff", LibraryAnnotationValue(Library(name = "oa_rvt_ff", voltage = 0.7, temperature = 0, nominalType = "ff",
      libertyFile = Some(???),
      voltageThreshold = Some("rvt"),
      qrcTechFile = Some(???),
      lefFile = Some(???),
      spiceFile = Some(???),
      gdsFile = Some(???)))),
    Annotation("system.library.asap7.libraries.seq_rvt_ss", LibraryAnnotationValue(Library(name = "seq_rvt_ss", voltage = 0.63, temperature = 100, nominalType = "ss",
      libertyFile = Some(???),
      voltageThreshold = Some("rvt"),
      qrcTechFile = Some(???),
      lefFile = Some(???),
      spiceFile = Some(???),
      gdsFile = Some(???)))),
    Annotation("system.library.asap7.libraries.seq_rvt_tt", LibraryAnnotationValue(Library(name = "seq_rvt_tt", voltage = 0.7, temperature = 25, nominalType = "tt",
      libertyFile = Some(???),
      voltageThreshold = Some("rvt"),
      qrcTechFile = Some(???),
      lefFile = Some(???),
      spiceFile = Some(???),
      gdsFile = Some(???)))),
    Annotation("system.library.asap7.libraries.seq_rvt_ff", LibraryAnnotationValue(Library(name = "seq_rvt_ff", voltage = 0.7, temperature = 0, nominalType = "ff",
      libertyFile = Some(???),
      voltageThreshold = Some("rvt"),
      qrcTechFile = Some(???),
      lefFile = Some(???),
      spiceFile = Some(???),
      gdsFile = Some(???)))),
    Annotation("system.library.asap7.libraries.simple_rvt_ss", LibraryAnnotationValue(Library(name = "simple_rvt_ss", voltage = 0.63, temperature = 100, nominalType = "ss",
      libertyFile = Some(???),
      voltageThreshold = Some("rvt"),
      qrcTechFile = Some(???),
      lefFile = Some(???),
      spiceFile = Some(???),
      gdsFile = Some(???)))),
    Annotation("system.library.asap7.libraries.simple_rvt_tt", LibraryAnnotationValue(Library(name = "simple_rvt_tt", voltage = 0.7, temperature = 25, nominalType = "tt",
      libertyFile = Some(???),
      voltageThreshold = Some("rvt"),
      qrcTechFile = Some(???),
      lefFile = Some(???),
      spiceFile = Some(???),
      gdsFile = Some(???)))),
    Annotation("system.library.asap7.libraries.simple_rvt_ff", LibraryAnnotationValue(Library(name = "simple_rvt_ff", voltage = 0.7, temperature = 0, nominalType = "ff",
      libertyFile = Some(???),
      voltageThreshold = Some("rvt"),
      qrcTechFile = Some(???),
      lefFile = Some(???),
      spiceFile = Some(???),
      gdsFile = Some(???)))),
    Annotation("system.library.asap7.libraries.ao_lvt_ss", LibraryAnnotationValue(Library(name = "ao_lvt_ss", voltage = 0.63, temperature = 100, nominalType = "ss",
      libertyFile = Some(???),
      voltageThreshold = Some("lvt"),
      qrcTechFile = Some(???),
      lefFile = Some(???),
      spiceFile = Some(???),
      gdsFile = Some(???)))),
    Annotation("system.library.asap7.libraries.ao_lvt_tt", LibraryAnnotationValue(Library(name = "ao_lvt_tt", voltage = 0.7, temperature = 25, nominalType = "tt",
      libertyFile = Some(???),
      voltageThreshold = Some("lvt"),
      qrcTechFile = Some(???),
      lefFile = Some(???),
      spiceFile = Some(???),
      gdsFile = Some(???)))),
    Annotation("system.library.asap7.libraries.ao_lvt_ff", LibraryAnnotationValue(Library(name = "ao_lvt_ff", voltage = 0.7, temperature = 0, nominalType = "ff",
      libertyFile = Some(???),
      voltageThreshold = Some("lvt"),
      qrcTechFile = Some(???),
      lefFile = Some(???),
      spiceFile = Some(???),
      gdsFile = Some(???)))),
    Annotation("system.library.asap7.libraries.invbuf_lvt_ss", LibraryAnnotationValue(Library(name = "invbuf_lvt_ss", voltage = 0.63, temperature = 100, nominalType = "ss",
      libertyFile = Some(???),
      voltageThreshold = Some("lvt"),
      qrcTechFile = Some(???),
      lefFile = Some(???),
      spiceFile = Some(???),
      gdsFile = Some(???)))),
    Annotation("system.library.asap7.libraries.invbuf_lvt_tt", LibraryAnnotationValue(Library(name = "invbuf_lvt_tt", voltage = 0.7, temperature = 25, nominalType = "tt",
      libertyFile = Some(???),
      voltageThreshold = Some("lvt"),
      qrcTechFile = Some(???),
      lefFile = Some(???),
      spiceFile = Some(???),
      gdsFile = Some(???)))),
    Annotation("system.library.asap7.libraries.invbuf_lvt_ff", LibraryAnnotationValue(Library(name = "invbuf_lvt_ff", voltage = 0.7, temperature = 0, nominalType = "ff",
      libertyFile = Some(???),
      voltageThreshold = Some("lvt"),
      qrcTechFile = Some(???),
      lefFile = Some(???),
      spiceFile = Some(???),
      gdsFile = Some(???)))),
    Annotation("system.library.asap7.libraries.oa_lvt_ss", LibraryAnnotationValue(Library(name = "oa_lvt_ss", voltage = 0.63, temperature = 100, nominalType = "ss",
      libertyFile = Some(???),
      voltageThreshold = Some("lvt"),
      qrcTechFile = Some(???),
      lefFile = Some(???),
      spiceFile = Some(???),
      gdsFile = Some(???)))),
    Annotation("system.library.asap7.libraries.oa_lvt_tt", LibraryAnnotationValue(Library(name = "oa_lvt_tt", voltage = 0.7, temperature = 25, nominalType = "tt",
      libertyFile = Some(???),
      voltageThreshold = Some("lvt"),
      qrcTechFile = Some(???),
      lefFile = Some(???),
      spiceFile = Some(???),
      gdsFile = Some(???)))),
    Annotation("system.library.asap7.libraries.oa_lvt_ff", LibraryAnnotationValue(Library(name = "oa_lvt_ff", voltage = 0.7, temperature = 0, nominalType = "ff",
      libertyFile = Some(???),
      voltageThreshold = Some("lvt"),
      qrcTechFile = Some(???),
      lefFile = Some(???),
      spiceFile = Some(???),
      gdsFile = Some(???)))),
    Annotation("system.library.asap7.libraries.seq_lvt_ss", LibraryAnnotationValue(Library(name = "seq_lvt_ss", voltage = 0.63, temperature = 100, nominalType = "ss",
      libertyFile = Some(???),
      voltageThreshold = Some("lvt"),
      qrcTechFile = Some(???),
      lefFile = Some(???),
      spiceFile = Some(???),
      gdsFile = Some(???)))),
    Annotation("system.library.asap7.libraries.seq_lvt_tt", LibraryAnnotationValue(Library(name = "seq_lvt_tt", voltage = 0.7, temperature = 25, nominalType = "tt",
      libertyFile = Some(???),
      voltageThreshold = Some("lvt"),
      qrcTechFile = Some(???),
      lefFile = Some(???),
      spiceFile = Some(???),
      gdsFile = Some(???)))),
    Annotation("system.library.asap7.libraries.seq_lvt_ff", LibraryAnnotationValue(Library(name = "seq_lvt_ff", voltage = 0.7, temperature = 0, nominalType = "ff",
      libertyFile = Some(???),
      voltageThreshold = Some("lvt"),
      qrcTechFile = Some(???),
      lefFile = Some(???),
      spiceFile = Some(???),
      gdsFile = Some(???)))),
    Annotation("system.library.asap7.libraries.simple_lvt_ss", LibraryAnnotationValue(Library(name = "simple_lvt_ss", voltage = 0.63, temperature = 100, nominalType = "ss",
      libertyFile = Some(???),
      voltageThreshold = Some("lvt"),
      qrcTechFile = Some(???),
      lefFile = Some(???),
      spiceFile = Some(???),
      gdsFile = Some(???)))),
    Annotation("system.library.asap7.libraries.simple_lvt_tt", LibraryAnnotationValue(Library(name = "simple_lvt_tt", voltage = 0.7, temperature = 25, nominalType = "tt",
      libertyFile = Some(???),
      voltageThreshold = Some("lvt"),
      qrcTechFile = Some(???),
      lefFile = Some(???),
      spiceFile = Some(???),
      gdsFile = Some(???)))),
    Annotation("system.library.asap7.libraries.simple_lvt_ff", LibraryAnnotationValue(Library(name = "simple_lvt_ff", voltage = 0.7, temperature = 0, nominalType = "ff",
      libertyFile = Some(???),
      voltageThreshold = Some("lvt"),
      qrcTechFile = Some(???),
      lefFile = Some(???),
      spiceFile = Some(???),
      gdsFile = Some(???)))),
    Annotation("system.library.asap7.libraries.ao_slvt_ss", LibraryAnnotationValue(Library(name = "ao_slvt_ss", voltage = 0.63, temperature = 100, nominalType = "ss",
      libertyFile = Some(???),
      voltageThreshold = Some("slvt"),
      qrcTechFile = Some(???),
      lefFile = Some(???),
      spiceFile = Some(???),
      gdsFile = Some(???)))),
    Annotation("system.library.asap7.libraries.ao_slvt_tt", LibraryAnnotationValue(Library(name = "ao_slvt_tt", voltage = 0.7, temperature = 25, nominalType = "tt",
      libertyFile = Some(???),
      voltageThreshold = Some("slvt"),
      qrcTechFile = Some(???),
      lefFile = Some(???),
      spiceFile = Some(???),
      gdsFile = Some(???)))),
    Annotation("system.library.asap7.libraries.ao_slvt_ff", LibraryAnnotationValue(Library(name = "ao_slvt_ff", voltage = 0.7, temperature = 0, nominalType = "ff",
      libertyFile = Some(???),
      voltageThreshold = Some("slvt"),
      qrcTechFile = Some(???),
      lefFile = Some(???),
      spiceFile = Some(???),
      gdsFile = Some(???)))),
    Annotation("system.library.asap7.libraries.invbuf_slvt_ss", LibraryAnnotationValue(Library(name = "invbuf_slvt_ss", voltage = 0.63, temperature = 100, nominalType = "ss",
      libertyFile = Some(???),
      voltageThreshold = Some("slvt"),
      qrcTechFile = Some(???),
      lefFile = Some(???),
      spiceFile = Some(???),
      gdsFile = Some(???)))),
    Annotation("system.library.asap7.libraries.invbuf_slvt_tt", LibraryAnnotationValue(Library(name = "invbuf_slvt_tt", voltage = 0.7, temperature = 25, nominalType = "tt",
      libertyFile = Some(???),
      voltageThreshold = Some("slvt"),
      qrcTechFile = Some(???),
      lefFile = Some(???),
      spiceFile = Some(???),
      gdsFile = Some(???)))),
    Annotation("system.library.asap7.libraries.invbuf_slvt_ff", LibraryAnnotationValue(Library(name = "invbuf_slvt_ff", voltage = 0.7, temperature = 0, nominalType = "ff",
      libertyFile = Some(???),
      voltageThreshold = Some("slvt"),
      qrcTechFile = Some(???),
      lefFile = Some(???),
      spiceFile = Some(???),
      gdsFile = Some(???)))),
    Annotation("system.library.asap7.libraries.oa_slvt_ss", LibraryAnnotationValue(Library(name = "oa_slvt_ss", voltage = 0.63, temperature = 100, nominalType = "ss",
      libertyFile = Some(???),
      voltageThreshold = Some("slvt"),
      qrcTechFile = Some(???),
      lefFile = Some(???),
      spiceFile = Some(???),
      gdsFile = Some(???)))),
    Annotation("system.library.asap7.libraries.oa_slvt_tt", LibraryAnnotationValue(Library(name = "oa_slvt_tt", voltage = 0.7, temperature = 25, nominalType = "tt",
      libertyFile = Some(???),
      voltageThreshold = Some("slvt"),
      qrcTechFile = Some(???),
      lefFile = Some(???),
      spiceFile = Some(???),
      gdsFile = Some(???)))),
    Annotation("system.library.asap7.libraries.oa_slvt_ff", LibraryAnnotationValue(Library(name = "oa_slvt_ff", voltage = 0.7, temperature = 0, nominalType = "ff",
      libertyFile = Some(???),
      voltageThreshold = Some("slvt"),
      qrcTechFile = Some(???),
      lefFile = Some(???),
      spiceFile = Some(???),
      gdsFile = Some(???)))),
    Annotation("system.library.asap7.libraries.seq_slvt_ss", LibraryAnnotationValue(Library(name = "seq_slvt_ss", voltage = 0.63, temperature = 100, nominalType = "ss",
      libertyFile = Some(???),
      voltageThreshold = Some("slvt"),
      qrcTechFile = Some(???),
      lefFile = Some(???),
      spiceFile = Some(???),
      gdsFile = Some(???)))),
    Annotation("system.library.asap7.libraries.seq_slvt_tt", LibraryAnnotationValue(Library(name = "seq_slvt_tt", voltage = 0.7, temperature = 25, nominalType = "tt",
      libertyFile = Some(???),
      voltageThreshold = Some("slvt"),
      qrcTechFile = Some(???),
      lefFile = Some(???),
      spiceFile = Some(???),
      gdsFile = Some(???)))),
    Annotation("system.library.asap7.libraries.seq_slvt_ff", LibraryAnnotationValue(Library(name = "seq_slvt_ff", voltage = 0.7, temperature = 0, nominalType = "ff",
      libertyFile = Some(???),
      voltageThreshold = Some("slvt"),
      qrcTechFile = Some(???),
      lefFile = Some(???),
      spiceFile = Some(???),
      gdsFile = Some(???)))),
    Annotation("system.library.asap7.libraries.simple_slvt_ss", LibraryAnnotationValue(Library(name = "simple_slvt_ss", voltage = 0.63, temperature = 100, nominalType = "ss",
      libertyFile = Some(???),
      voltageThreshold = Some("slvt"),
      qrcTechFile = Some(???),
      lefFile = Some(???),
      spiceFile = Some(???),
      gdsFile = Some(???)))),
    Annotation("system.library.asap7.libraries.simple_slvt_tt", LibraryAnnotationValue(Library(name = "simple_slvt_tt", voltage = 0.7, temperature = 25, nominalType = "tt",
      libertyFile = Some(???),
      voltageThreshold = Some("slvt"),
      qrcTechFile = Some(???),
      lefFile = Some(???),
      spiceFile = Some(???),
      gdsFile = Some(???)))),
    Annotation("system.library.asap7.libraries.simple_slvt_ff", LibraryAnnotationValue(Library(name = "simple_slvt_ff", voltage = 0.7, temperature = 0, nominalType = "ff",
      libertyFile = Some(???),
      voltageThreshold = Some("slvt"),
      qrcTechFile = Some(???),
      lefFile = Some(???),
      spiceFile = Some(???),
      gdsFile = Some(???)))),
    Annotation("system.library.asap7.libraries.ao_sram_ss", LibraryAnnotationValue(Library(name = "ao_sram_ss", voltage = 0.63, temperature = 100, nominalType = "ss",
      libertyFile = Some(???),
      voltageThreshold = Some("sram"),
      qrcTechFile = Some(???),
      lefFile = Some(???),
      spiceFile = Some(???),
      gdsFile = Some(???)))),
    Annotation("system.library.asap7.libraries.ao_sram_tt", LibraryAnnotationValue(Library(name = "ao_sram_tt", voltage = 0.7, temperature = 25, nominalType = "tt",
      libertyFile = Some(???),
      voltageThreshold = Some("sram"),
      qrcTechFile = Some(???),
      lefFile = Some(???),
      spiceFile = Some(???),
      gdsFile = Some(???)))),
    Annotation("system.library.asap7.libraries.ao_sram_ff", LibraryAnnotationValue(Library(name = "ao_sram_ff", voltage = 0.7, temperature = 0, nominalType = "ff",
      libertyFile = Some(???),
      voltageThreshold = Some("sram"),
      qrcTechFile = Some(???),
      lefFile = Some(???),
      spiceFile = Some(???),
      gdsFile = Some(???)))),
    Annotation("system.library.asap7.libraries.invbuf_sram_ss", LibraryAnnotationValue(Library(name = "invbuf_sram_ss", voltage = 0.63, temperature = 100, nominalType = "ss",
      libertyFile = Some(???),
      voltageThreshold = Some("sram"),
      qrcTechFile = Some(???),
      lefFile = Some(???),
      spiceFile = Some(???),
      gdsFile = Some(???)))),
    Annotation("system.library.asap7.libraries.invbuf_sram_tt", LibraryAnnotationValue(Library(name = "invbuf_sram_tt", voltage = 0.7, temperature = 25, nominalType = "tt",
      libertyFile = Some(???),
      voltageThreshold = Some("sram"),
      qrcTechFile = Some(???),
      lefFile = Some(???),
      spiceFile = Some(???),
      gdsFile = Some(???)))),
    Annotation("system.library.asap7.libraries.invbuf_sram_ff", LibraryAnnotationValue(Library(name = "invbuf_sram_ff", voltage = 0.7, temperature = 0, nominalType = "ff",
      libertyFile = Some(???),
      voltageThreshold = Some("sram"),
      qrcTechFile = Some(???),
      lefFile = Some(???),
      spiceFile = Some(???),
      gdsFile = Some(???)))),
    Annotation("system.library.asap7.libraries.oa_sram_ss", LibraryAnnotationValue(Library(name = "oa_sram_ss", voltage = 0.63, temperature = 100, nominalType = "ss",
      libertyFile = Some(???),
      voltageThreshold = Some("sram"),
      qrcTechFile = Some(???),
      lefFile = Some(???),
      spiceFile = Some(???),
      gdsFile = Some(???)))),
    Annotation("system.library.asap7.libraries.oa_sram_tt", LibraryAnnotationValue(Library(name = "oa_sram_tt", voltage = 0.7, temperature = 25, nominalType = "tt",
      libertyFile = Some(???),
      voltageThreshold = Some("sram"),
      qrcTechFile = Some(???),
      lefFile = Some(???),
      spiceFile = Some(???),
      gdsFile = Some(???)))),
    Annotation("system.library.asap7.libraries.oa_sram_ff", LibraryAnnotationValue(Library(name = "oa_sram_ff", voltage = 0.7, temperature = 0, nominalType = "ff",
      libertyFile = Some(???),
      voltageThreshold = Some("sram"),
      qrcTechFile = Some(???),
      lefFile = Some(???),
      spiceFile = Some(???),
      gdsFile = Some(???)))),
    Annotation("system.library.asap7.libraries.seq_sram_ss", LibraryAnnotationValue(Library(name = "seq_sram_ss", voltage = 0.63, temperature = 100, nominalType = "ss",
      libertyFile = Some(???),
      voltageThreshold = Some("sram"),
      qrcTechFile = Some(???),
      lefFile = Some(???),
      spiceFile = Some(???),
      gdsFile = Some(???)))),
    Annotation("system.library.asap7.libraries.seq_sram_tt", LibraryAnnotationValue(Library(name = "seq_sram_tt", voltage = 0.7, temperature = 25, nominalType = "tt",
      libertyFile = Some(???),
      voltageThreshold = Some("sram"),
      qrcTechFile = Some(???),
      lefFile = Some(???),
      spiceFile = Some(???),
      gdsFile = Some(???)))),
    Annotation("system.library.asap7.libraries.seq_sram_ff", LibraryAnnotationValue(Library(name = "seq_sram_ff", voltage = 0.7, temperature = 0, nominalType = "ff",
      libertyFile = Some(???),
      voltageThreshold = Some("sram"),
      qrcTechFile = Some(???),
      lefFile = Some(???),
      spiceFile = Some(???),
      gdsFile = Some(???)))),
    Annotation("system.library.asap7.libraries.simple_sram_ss", LibraryAnnotationValue(Library(name = "simple_sram_ss", voltage = 0.63, temperature = 100, nominalType = "ss",
      libertyFile = Some(???),
      voltageThreshold = Some("sram"),
      qrcTechFile = Some(???),
      lefFile = Some(???),
      spiceFile = Some(???),
      gdsFile = Some(???)))),
    Annotation("system.library.asap7.libraries.simple_sram_tt", LibraryAnnotationValue(Library(name = "simple_sram_tt", voltage = 0.7, temperature = 25, nominalType = "tt",
      libertyFile = Some(???),
      voltageThreshold = Some("sram"),
      qrcTechFile = Some(???),
      lefFile = Some(???),
      spiceFile = Some(???),
      gdsFile = Some(???)))),
    Annotation("system.library.asap7.libraries.simple_sram_ff", LibraryAnnotationValue(Library(name = "simple_sram_ff", voltage = 0.7, temperature = 0, nominalType = "ff",
      libertyFile = Some(???),
      voltageThreshold = Some("sram"),
      qrcTechFile = Some(???),
      lefFile = Some(???),
      spiceFile = Some(???),
      gdsFile = Some(???))))
  )

  override def transform: ScratchPad = {
    val s = scratchPadIn
    s.get("user.input.pdk.name") match {
      case None => s
      case Some(PDKNameAnnotationValue("asap7")) =>
        s.get("user.input.pdk.cache_dir") match {
          case None => s.get("user.input.pdk.download_dir") match {
            case None => throw LibraryNotFoundException
            case Some(DirectoryPathAnnotationValue(d)) =>
              s add
                Annotation("runtime.untar.tars", TarsPathAnnotationValue(Seq(d))) add
                Annotation("runtime.untar.internal_tars", RelTarsPathAnnotationValue(Seq(
                  RelPath("ASAP7_PDKandLIB.tar/ASAP7_PDKandLIB_v1p5/asap7libs_24.tar.bz2"),
                  RelPath("ASAP7_PDKandLIB.tar/ASAP7_PDKandLIB_v1p5/asap7PDK_r1p5.tar.bz2")
                ))) add
                Annotation("system.library.asap7.base_path", DirectoryPathAnnotationValue(tarCache)) add
                asap7Annotations
          }
          case Some(DirectoryPathAnnotationValue(d)) =>
            s delete
              "user.input.pdk.tars" add
              Annotation("system.library.base_path", DirectoryPathAnnotationValue(d))
        }
    }

  }
}

case class ASAP7Stage(scratchPadIn: ScratchPad) extends Stage {
  def phases: Seq[ScratchPad => Phase] = Seq(
    DigestASPA7LibraryAnnotation,
    UntarStage
  )
}